import { useMemo, useState } from "react";
import metadata from "./data/dataset-metadata.json";
import effectorData from "./data/effectors.json";
import interactionData from "./data/interactions.json";
import nlrData from "./data/nlrs.json";

type Effector = { id:string; inputId:string; alias:string; index:number; length:number; sequence:string };
type Nlr = { id:string; inputId:string; length:number; sequence:string; nlrClass:string };
type Pair = { id:string; pairIndex:number; effector:string; effectorInputId:string; nlr:string; nlrInputId:string; megadockScore:number; globalRank:number; globalPercentile:number; effectorRank:number; nlrRank:number; selectedGlobalTop2Pct:boolean; selectedEffectorTop3:boolean; selectedNlrTop3:boolean; selectionSources:string[]; effectorMeanPlddt:number; nlrMeanPlddt:number; kingdom:string; species:string };
const effectors = effectorData as Effector[];
const nlrs = nlrData as Nlr[];
const pairs = interactionData as Pair[];
const integer = new Intl.NumberFormat("en-US");

function fasta(header:string, sequence:string) { return `>${header}\n${sequence.match(/.{1,60}/g)?.join("\n") ?? ""}\n`; }
function crc32(bytes: Uint8Array) { let crc = 0xffffffff; for (const byte of bytes) { crc ^= byte; for (let i=0;i<8;i++) crc = (crc>>>1) ^ (0xedb88320 & -(crc&1)); } return (crc ^ 0xffffffff) >>> 0; }
function u16(n:number) { return [n&255,(n>>>8)&255]; } function u32(n:number) { return [n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]; }
function zip(files:{name:string; text:string}[]) {
  const encoder=new TextEncoder(), local:number[]=[], central:number[]=[], entries:{name:Uint8Array; data:Uint8Array; crc:number; offset:number}[]=[];
  for (const file of files) { const name=encoder.encode(file.name), data=encoder.encode(file.text), offset=local.length, crc=crc32(data); entries.push({name,data,crc,offset}); local.push(...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...name,...data); }
  const centralOffset=local.length;
  for (const e of entries) central.push(...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(e.crc),...u32(e.data.length),...u32(e.data.length),...u16(e.name.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(e.offset),...e.name);
  return new Blob([new Uint8Array([...local,...central,...u32(0x06054b50),...u16(0),...u16(0),...u16(entries.length),...u16(entries.length),...u32(central.length),...u32(centralOffset),...u16(0)])],{type:"application/zip"});
}
function download(name:string, blob:Blob) { const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); }
function badges(pair:Pair) { return <div className="selection-badges">{pair.selectedGlobalTop2Pct&&<span>Global top 2%</span>}{pair.selectedEffectorTop3&&<span>Effector top 3</span>}{pair.selectedNlrTop3&&<span>NLR top 3</span>}</div>; }

export default function App() {
  const [entered,setEntered]=useState(false); const [nlrClass,setNlrClass]=useState("All"); const [nlrQuery,setNlrQuery]=useState(""); const [kingdom,setKingdom]=useState("Fungi"); const [species,setSpecies]=useState("Fusarium"); const [sort,setSort]=useState("score"); const [perPage,setPerPage]=useState(20); const [page,setPage]=useState(1); const [checked,setChecked]=useState<Set<string>>(new Set()); const [selected,setSelected]=useState<Pair>(pairs[0]);
  const nlrById=useMemo(()=>new Map(nlrs.map(x=>[x.id,x])),[]); const effectorById=useMemo(()=>new Map(effectors.map(x=>[x.id,x])),[]);
  const classes=useMemo(()=>["All",...Array.from(new Set(nlrs.map(x=>x.nlrClass))).sort()],[]);
  const availableNlrs=useMemo(()=>nlrs.filter(n=>nlrClass==="All"||n.nlrClass===nlrClass),[nlrClass]);
  const filtered=useMemo(()=>pairs.filter(p=>kingdom===p.kingdom).filter(p=>species===p.species).filter(p=>nlrClass==="All"||nlrById.get(p.nlr)?.nlrClass===nlrClass).filter(p=>!nlrQuery||p.nlr.toLowerCase().includes(nlrQuery.toLowerCase())||p.nlrInputId.toLowerCase().includes(nlrQuery.toLowerCase())).sort((a,b)=>sort==="rank"?a.globalRank-b.globalRank:sort==="nlr"?a.nlr.localeCompare(b.nlr):b.megadockScore-a.megadockScore),[kingdom,species,nlrClass,nlrQuery,sort,nlrById]);
  const pageCount=Math.max(1,Math.ceil(filtered.length/perPage)); const activePage=Math.min(page,pageCount); const rows=filtered.slice((activePage-1)*perPage,activePage*perPage);
  const choose=(pair:Pair)=>setSelected(pair); const toggle=(id:string)=>setChecked(prev=>{const next=new Set(prev); next.has(id)?next.delete(id):next.add(id); return next;});
  const togglePage=()=>setChecked(prev=>{const next=new Set(prev), all=rows.every(x=>next.has(x.id)); rows.forEach(x=>all?next.delete(x.id):next.add(x.id)); return next;});
  const exportSelected=()=>{ const chosen=pairs.filter(x=>checked.has(x.id)); if(!chosen.length) return; const proteins=new Map<string,{header:string;sequence:string}>(); chosen.forEach(p=>{const n=nlrById.get(p.nlr)!; const e=effectorById.get(p.effector)!; proteins.set(`NLR:${n.id}`,{header:`${n.id} | ${n.nlrClass} | ${n.length} aa`,sequence:n.sequence}); proteins.set(`Effector:${e.id}`,{header:`${e.alias} | ${e.inputId} | ${e.length} aa`,sequence:e.sequence});}); const evidence=["interaction_pair\tnlr_id\tnlr_class\tnlr_length_aa\teffector_alias\teffector_accession\teffector_length_aa\tmegadock_score\tglobal_rank\teffector_rank\tnlr_rank\tselection_basis",...chosen.map(p=>{const n=nlrById.get(p.nlr)!;const e=effectorById.get(p.effector)!;return [`${n.id}—${e.alias}`,n.id,n.nlrClass,n.length,e.alias,e.inputId,e.length,p.megadockScore,p.globalRank,p.effectorRank,p.nlrRank,p.selectionSources.join(";")].join("\t")})].join("\n")+"\n"; const sequenceText=Array.from(proteins.values()).map(x=>fasta(x.header,x.sequence)).join(""); download("MaizeNEID_selected_pairs.zip",zip([{name:"MaizeNEID_selected_protein_sequences.fasta",text:sequenceText},{name:"MaizeNEID_selected_interaction_evidence.tsv",text:evidence}])); };
  const title=<><span><b>M</b>aize</span> <span><b>N</b>LR-<b>E</b>ffector</span><br/><span><b>I</b>nteract <b>D</b>atabase</span></>;
  if(!entered) return <main className="welcome-page"><nav className="welcome-nav"><div className="welcome-identity"><img className="szu-logo welcome-logo" src="/shenzhen-university-emblem.svg" alt="Shenzhen University"/><div className="brand inverse"><span className="mark">N</span><span>MaizeNEID<small>Yang Lab</small></span></div></div><span>CURATED PRECOMPUTED EVIDENCE</span></nav><section className="welcome-content"><p className="welcome-kicker">YANG LAB</p><h1 className="full-title">{title}</h1><p className="welcome-acronym">MaizeNEID</p><p className="welcome-subtitle">A curated resource for precomputed interaction evidence between maize immune receptors and pathogen Effector candidates.</p><div className="welcome-actions"><button onClick={()=>setEntered(true)}>Enter the database <span>→</span></button><span className="citation-pending">Citation DOI pending assignment</span></div></section><div className="welcome-footer"><span>PRECOMPUTED EVIDENCE</span><span>AF-MULTIMER PENDING</span><span>ALPHAFOLD 3 PENDING</span><span>NO ONLINE ANALYSIS</span></div></main>;
  return <main><nav className="topbar"><div className="topbar-identity"><img className="szu-logo topbar-logo" src="/shenzhen-university-emblem.svg" alt="Shenzhen University"/><div className="brand"><span className="mark">N</span><span>MaizeNEID<small>Yang Lab</small></span></div></div><div className="navlinks"><a href="#evidence">Evidence browser</a><a href="#about">Data provenance</a></div></nav><section className="hero"><p className="eyebrow">YANG LAB / CURATED PRECOMPUTED EVIDENCE</p><h1>{title}</h1><p className="hero-copy">Browse imported candidate interactions between maize immune receptors and pathogen Effectors. Evidence types are added as completed results become available.</p><div className="hero-metrics"><div><strong>{integer.format(metadata.effectorCount)}</strong><span>Fusarium effectors</span></div><div><strong>{integer.format(metadata.nlrCount)}</strong><span>maize receptor proteins</span></div><div><strong>{integer.format(metadata.selectedInteractionCount)}</strong><span>AF-Multimer input pairs</span></div><div><strong>01</strong><span>evidence channel available</span></div></div></section>
  <section id="evidence" className="matrix-section"><div className="section-heading"><div><p className="eyebrow">NLR-CENTRIC BROWSER</p><h2>Candidate interaction evidence</h2></div><p>Only pre-filtered pairs submitted to the current AF-Multimer input set are displayed.</p></div><div className="matrix-controls data-filters"><label><span>NLR class</span><select value={nlrClass} onChange={e=>{setNlrClass(e.target.value);setNlrQuery("");setPage(1)}}>{classes.map(x=><option key={x}>{x}</option>)}</select></label><label><span>NLR protein ID</span><input list="nlr-options" value={nlrQuery} onChange={e=>{setNlrQuery(e.target.value);setPage(1)}} placeholder="Search Zm protein ID"/><datalist id="nlr-options">{availableNlrs.map(n=><option key={n.id} value={n.id}>{n.nlrClass}</option>)}</datalist></label><label><span>Pathogen group</span><select value={kingdom} onChange={e=>{setKingdom(e.target.value);setSpecies(e.target.value==="Fungi"?"Fusarium":"None");setPage(1)}}><option>Fungi</option><option>Bacteria</option></select></label><label><span>Pathogen taxon</span><select value={species} onChange={e=>{setSpecies(e.target.value);setPage(1)}} disabled={kingdom!=="Fungi"}><option value="Fusarium">Fusarium</option>{kingdom!=="Fungi"&&<option value="None">No imported taxa</option>}</select></label><label><span>Sort</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="score">MEGADOCK score</option><option value="rank">Global rank</option><option value="nlr">NLR identifier</option></select></label></div>
  <div className="matrix-card"><div className="matrix-meta"><div><small>FILTERED, PRECOMPUTED CANDIDATES</small><h3>{integer.format(filtered.length)} interaction pairs</h3><p>Current selection policy: global top 2% ∪ Effector top 3 ∪ NLR top 3.</p></div><button className="download-button" disabled={!checked.size} onClick={exportSelected}>Download selected ({checked.size})</button></div><div className="matrix-scroll"><table className="evidence-table real-evidence-table"><thead><tr><th><input aria-label="Select current page" type="checkbox" checked={rows.length>0&&rows.every(x=>checked.has(x.id))} onChange={togglePage}/></th><th>Interaction pair</th><th>Candidate NLR</th><th>Effector</th><th>MEGADOCK evidence</th><th>AF-Multimer evidence</th><th>AlphaFold 3 evidence</th><th>Selection basis</th></tr></thead><tbody>{rows.map(p=>{const n=nlrById.get(p.nlr)!;const e=effectorById.get(p.effector)!;return <tr key={p.id} className={selected.id===p.id?"selected":""} onClick={()=>choose(p)}><td onClick={event=>event.stopPropagation()}><input aria-label={`Select ${p.id}`} type="checkbox" checked={checked.has(p.id)} onChange={()=>toggle(p.id)}/></td><td><b>{n.id}—{e.alias}</b><small>{p.id}</small></td><td><b>{n.id}</b><small>{n.nlrClass} · {n.length} aa · monomer pLDDT {p.nlrMeanPlddt.toFixed(2)}</small></td><td><b>{e.alias}</b><small>{e.length} aa · monomer pLDDT {p.effectorMeanPlddt.toFixed(2)}</small></td><td><div className="megadock-cell"><b>{p.megadockScore.toFixed(2)}</b><span>Global #{integer.format(p.globalRank)} · Effector #{p.effectorRank} · NLR #{p.nlrRank}</span></div></td><td><div className="unavailable-cell"><b>Pending</b><span>Input submitted</span></div></td><td><div className="unavailable-cell"><b>Not available</b><span>Awaiting import</span></div></td><td>{badges(p)}</td></tr>})}{!rows.length&&<tr className="empty-row"><td colSpan={8}>No imported candidate pairs match the selected filters.</td></tr>}</tbody></table></div><div className="table-footer"><label>Rows per page <select value={perPage} onChange={e=>{setPerPage(Number(e.target.value));setPage(1)}}>{[20,50,100].map(x=><option key={x}>{x}</option>)}</select></label><div><button disabled={activePage===1} onClick={()=>setPage(activePage-1)}>Previous</button><span>Page {activePage} / {pageCount}</span><button disabled={activePage===pageCount} onClick={()=>setPage(activePage+1)}>Next</button></div></div><div className="matrix-note"><b>Download package.</b> A ZIP contains FASTA sequences for unique selected proteins and a TSV evidence table for the checked interaction pairs. MEGADOCK is the only completed evidence type in this release.</div></div></section>
  <section className="explore-shell"><div className="section-heading"><div><p className="eyebrow">PAIR RECORD</p><h2>{nlrById.get(selected.nlr)?.id} <span className="muted-x">×</span> {effectorById.get(selected.effector)?.alias}</h2></div><p>{selected.id}</p></div><article className="detail-card wide real-pair-card"><div className="detail-head"><div><p className="eyebrow">AVAILABLE EVIDENCE: MEGADOCK</p><h2>Docking score {selected.megadockScore.toFixed(2)}</h2><p>Global rank #{integer.format(selected.globalRank)} among all scored docking pairs.</p></div></div><div className="record-grid"><div><span>NLR class</span><b>{nlrById.get(selected.nlr)?.nlrClass}</b></div><div><span>NLR monomer pLDDT</span><b>{selected.nlrMeanPlddt.toFixed(2)}</b></div><div><span>Effector monomer pLDDT</span><b>{selected.effectorMeanPlddt.toFixed(2)}</b></div></div><div className="honest-empty-state"><span>3D</span><div><h3>No complex structure is available</h3><p>Complex models and interface residues will appear only after AF-Multimer or AlphaFold 3 results are imported.</p></div></div></article></section><section id="about" className="about"><p className="eyebrow">YANG LAB / DATA PROVENANCE</p><h2>Only completed, traceable evidence is displayed.</h2><p>The current release contains {integer.format(metadata.selectedInteractionCount)} candidate pairs from the latest <code>union_g2_e3_n3</code> selection: global top 2% ∪ Effector top 3 ∪ NLR top 3. It intentionally contains no fabricated complex structures, interface contacts, hydrogen bonds, AF-Multimer scores, or AlphaFold 3 scores.</p></section><footer>Maize NLR-Effector Interact Database (MaizeNEID) <span>Yang Lab / dataset retrieved {metadata.retrievedOn}</span></footer></main>;
}
